### PR TITLE
Package rewrite circleci

### PR DESCRIPTION
**Pull request by JSchoenbachler**
Adds testing and CircleCI config for pushing to drat.

### CODE REVIEW

**Comment by jakejh** [comment]
There seems to be a lot of redundancy in the test_metapredict_*.R files. Can you consolidate them?

Also, this is a minor point, but I typically use camel case in file names.

**Comment by jakejh** [comment]
Please keep the bhattacharjee files as cel.gz (not just CEL) to reduce the size of the package.

**Comment by JSchoenbachler** [comment]
Could you elaborate on how you want me to consolidate them? I have them in separate files to be separately testing each R script file. I also used snake case because that is what the R script file names follow, and just added "_test"  to them to keep in suit. The data files in the test_data folder all use camelCase, the exceptions being the ones I didn't create and just edited or placed there.

RE: Bhattacharjee files, I will do that!

**Comment by jakejh** [comment]
Why not put those tests in the same R file? Then if we change the setup code, we don't have to change it three times.

**Comment by JSchoenbachler** [comment]
Are you just specifically talking about the setup at the beginning of each test file? Upon looking into that, would you be okay with me just creating a helper test file here that does it for all tests: https://github.com/r-lib/testthat/issues/422#issuecomment-200321137

**Comment by JSchoenbachler** [comment]
Actually, upon further inspection, it looks like they aren't recommended to be used anymore. I could still use them, though I don't know if they have plans of deprecating them or not. Alternatively, I could just put a script in the R folder for this: https://testthat.r-lib.org/reference/test_dir.html#special-files

**Comment by jakejh** [comment]
Yes, I'm referring to the code prior to the `test_that` calls. I don't think we need a helper file, just put all the `test_that` calls in one file. What's wrong with that?

**Comment by JSchoenbachler** [comment]
I just don't think it's best practice to put them all in a single file, see here: https://r-pkgs.org/tests.html#test-files

I added a setup.R file locally, that loads it all at once at the beginning of the test then runs all tests. Does that work?

EDIT: it should be noted that the setup files are still recommended.

**Comment by JSchoenbachler** [comment]
@jakejh do you have any other feedback, changes, or anything else that you feel needs addressing before we merge?

**Comment by jakejh** [comment]
Based on pmparser (https://github.com/hugheylab/pmparser/blob/master/DESCRIPTION), should `covr` go in the suggests section? Oddly, the description file for simphony does not have covr.

**Comment by JSchoenbachler** [comment]
I don't really know what you prefer, but I feel like covr is only used on CircleCI, and therefore not really used in conjunction with the package. withr is different since it's actually used every time it is tested/checked. What do you think?

**Comment by jakejh** [comment]
But can't you use it to calculate code coverage locally too?

**Comment by JSchoenbachler** [comment]
Look at this section: https://r-pkgs.org/description.html#dependencies

Specifically this part: 
'Suggests: your package can use these packages, but doesn’t require them. You might use suggested packages for example datasets, to run tests, build vignettes, or maybe there’s only one function that needs the package.'

I feel like we probably don't need to include it in the suggests, because it is only used for our own edification and coverage percentage calculations, and isn't referenced anywhere in the code. We only use it as a tool in our CircleCI run and to show as a badge on our readme.

**Comment by jakejh** [comment]
Most of the tidyverse and r-lib packages seem to have covr in Suggests, though, as does cowplot. I think that would be my preference.

**Comment by JSchoenbachler** [comment]
Okay, it has been added here. I'll do it to the other repos as well.

**Comment by jakejh** [comment]
Thanks. Remember to take the install.packages call out of the config yaml.

**Comment by jakejh** [comment]
Ok, I'd say go ahead and merge the pull request and let's see how it goes.

**Pull request merged**
